### ISSUE TITLE
GTK based GUI possible?

### ISSUE THREAD

**Issue by Sinasta** [nidhaloff/igel-ui#3]
I would like to thank you for your awesome work. I would like to know if it is possible (or already WIP) to have the GUI made in GTK or QT? It would allow a perfect integration into almost every linux distro themingwise. Thanks a lot!

**Comment by nidhaloff** [comment]
@Sinasta Hi, thanks for the kind words ;)

If you are asking whether it is possible to make a GUI using GTK or QT, then the answer is yes of course. However, there is no WIP for this (at the moment). Can you elaborate on why is this needed? 

The current UI (first release) is developed using electron, which is a cross-platform already, so it will work perfectly on (almost?) every Linux distro and on windows, macOS.. as well. So I'm wondering why would we need another GUI in GTK or QT? It would be helpful if you can explain your thoughts further.

**Comment by Sinasta** [comment]
Thank you for your answer. I am certainly not the best to explain the advantages of GTK or qt over electron. And i have to admit that i dont know anything on the development effort for making the gui in gtk or qt. My reson would be that i try to keep my distro as clean as possible. So i try to not use electron gui's. And my second reason is that system wide themes are working with gtk and qt. But i totally get your reason for using electron. Thanks anyway

**Comment by nidhaloff** [comment]
I'm not familiar with GTK. I played a bit with QT in the past but I have done nothing serious with it. So this would be a time consuming process, but maybe we will consider it if there are good reasons. The thing is you didn't give any good reasons until now. Can you please elaborate and explain your use case or the why?  

Besides, I have two questions regarding your last response:

- What do you mean with keeping your distro as clean as possible?

- Whats wrong with electron? What are your reasons for not using electron

- Please explain your use case exaclty and give concrete examples if you can

**Comment by Sinasta** [comment]
My reasons are maybe naive and doesn't justify a big effort in rewriting the GUI. 1. reason would be the visual integration in the rest of the os. this probably only counts on linux and maybe mac. electron isnt applying amy of the sytemwide theme.
And the second reason would be that as far as i know (sorry if im wrong) electron bundles (light) chrome and nodejs which are two packages which i would only use for Igel-ui. So it would require to install some dependencies. Maybe it is just me but 90% of my installed software is gtk based 10% Qt and none uses electron.

**Comment by nidhaloff** [comment]
@Sinasta Well, most igel users don't actually care about the theme and similar things. You are right electron has dependencies but I would 99.99% of the users are fine with it. Most people use electron apps already like vs code, Atom, MS Teams, etc..

So to be honest, your use case is very special and I'm not sure if I will ever consider investing much time in it. However, you can always checkout the source code and try to build an app yourself. Maybe many people will contribute and help you develop the app if they have similar use cases ;) 

I will close the issue now but feel free to re-open or create new issues if you want to discuss this further
